---
- name: scp files
  unarchive: src=files/elasticsearch_exporter-1.1.0.linux-amd64.tar.gz dest=/opt/

- name: scp start server config
  template: src=es_exporter.service dest=/lib/systemd/system/es_exporter.service

- name: start server2
  systemd: name=es_exporter state=started enabled=yes daemon_reload=yes
